### ISSUE TITLE
how to handle client disconnect?

### ISSUE THREAD

**Issue by acthp** [lynaghk/jetty7-websockets-async#8]
I haven't found a way to stop the 'go' block that is sending messages to the client, when the client disconnects (e.g. user closes tab). Looks like the :in channel is closed by the onClose method, but core.async doesn't expose this information to the caller.

**Comment by lynaghk** [comment]
I'm not sure if I'm following your situation.
Are you talking about [this](https://github.com/lynaghk/jetty7-websockets-async/blob/ddfb01fb836e9403491afd45667efd86753f5e6e/src/clj/com/keminglabs/jetty7_websockets_async/core.clj#L17) go block?

It looks to me like that block will end when the `in` port is closed, because then it will return `nil`, which will cause the "then" clause of the `if` to be followed, and that clause doesn't `recur` --- so the go will end.

Does that help?

**Comment by acthp** [comment]
I meant a similar loop in the application code, that's pushing notifications to the client. Turns out the build had an ancient version of core.async in which the return of >! was always nil, so there was no way to exit the loop. After upgrade, `(when (>! client msg) (recur))` works.

**Comment by lynaghk** [comment]
Cool, glad you got it worked out. Hope you've found this library useful.
